In [1]:
import json
import pandas as pd
from pathlib import Path

In [2]:
reg = []
for file in Path("../bronze/data/records").glob("*.jsonl"):
    with open(file, encoding="utf-8") as f:
        for line in f:
            payload = json.loads(line)
            reg.extend(payload["results"])

In [3]:
df = pd.DataFrame(pd.json_normalize(reg))

In [4]:
raw_lines, raw_columns = df.shape

In [5]:
df = df.drop_duplicates(subset="id", keep="last")

In [6]:
df.head()

,adref,created,__CLASS__,redirect_url,description,id,salary_is_predicted,title,company.__CLASS__,company.display_name,category.tag,category.__CLASS__,category.label,location.area,location.__CLASS__,location.display_name,latitude,longitude
20,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYXY0Nk1aU0E4Ukc5U...,2026-06-10T17:36:26Z,Adzuna::API::Response::Job,https://www.adzuna.com.br/land/ad/5758781254?s...,"Responsabilidades e atribuições: Definir, evol...",5758781254,0,Arquiteto de Dados Sr.,Adzuna::API::Response::Company,UOL EdTech,unknown,Adzuna::API::Response::Category,Unknown,"[Brasil, Sudeste, Estado de São Paulo, São Paulo]",Adzuna::API::Response::Location,"São Paulo, Estado de São Paulo",NaN,NaN
21,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYXY0Nk1aU0E4Ukc5U...,2026-07-10T15:01:03Z,Adzuna::API::Response::Job,https://www.adzuna.com.br/land/ad/5795881134?s...,A Engesoftware está em busca de um Administraç...,5795881134,0,Administração de Dados - Risco,Adzuna::API::Response::Company,Engesoftware Tecnologia S.A,it-jobs,Adzuna::API::Response::Category,Vagas em Tecnologia Informática,[Brasil],Adzuna::API::Response::Location,Brasil,NaN,NaN
22,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYXY0Nk1aU0E4Ukc5U...,2026-07-15T09:32:10Z,Adzuna::API::Response::Job,https://www.adzuna.com.br/land/ad/5801146046?s...,A Iguatemi Empresa de Shopping Centers S.A. é ...,5801146046,0,ANALISTA DE GOVERNANÇA DE DADOS SR.,Adzuna::API::Response::Company,Iguatemi S.A.,retail-jobs,Adzuna::API::Response::Category,Vagas em Varejo,"[Brasil, Sudeste, Estado de São Paulo, São Paulo]",Adzuna::API::Response::Location,"São Paulo, Estado de São Paulo",NaN,NaN
23,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYXY0Nk1aU0E4Ukc5U...,2026-07-05T17:03:19Z,Adzuna::API::Response::Job,https://www.adzuna.com.br/land/ad/5789297995?s...,Venha para uma das maiores empresas de Serviç...,5789297995,0,Engenheiro de Dados Sênior – Databricks,Adzuna::API::Response::Company,Tata Consultancy Services,it-jobs,Adzuna::API::Response::Category,Vagas em Tecnologia Informática,[Brasil],Adzuna::API::Response::Location,Brasil,NaN,NaN
24,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTc4ODIyMjM1MSIsI...,2026-07-04T16:53:37Z,Adzuna::API::Response::Job,https://www.adzuna.com.br/land/ad/5788222351?s...,CLT Local: Campinas SP Modelo: presencial Sobr...,5788222351,0,Gerente de Dados I | SAP,Adzuna::API::Response::Company,AB InBev,it-jobs,Adzuna::API::Response::Category,Vagas em Tecnologia Informática,"[Brasil, Sudeste, Estado de São Paulo, Campinas]",Adzuna::API::Response::Location,"Campinas, Estado de São Paulo",-22.98889,-47.14058

In [16]:
new_lines, new_columns = df.shape

print(f"{raw_lines - new_lines} lines were deleted")

20 lines were deleted

In [8]:
df = df.drop(columns = ["adref", "__CLASS__", "company.__CLASS__", "category.label", "category.tag", "location.area", "category.__CLASS__", "location.__CLASS__"])

In [11]:
df = df.rename(columns={'created':"collected_at", 'redirect_url':"url", 'salary_is_predicted':"salary", 'company.display_name':"company",'location.area':"local", 'location.display_name':"location"})

In [12]:
df.head()

,collected_at,url,description,id,salary,title,company,location,latitude,longitude
20,2026-06-10T17:36:26Z,https://www.adzuna.com.br/land/ad/5758781254?s...,"Responsabilidades e atribuições: Definir, evol...",5758781254,0,Arquiteto de Dados Sr.,UOL EdTech,"São Paulo, Estado de São Paulo",NaN,NaN
21,2026-07-10T15:01:03Z,https://www.adzuna.com.br/land/ad/5795881134?s...,A Engesoftware está em busca de um Administraç...,5795881134,0,Administração de Dados - Risco,Engesoftware Tecnologia S.A,Brasil,NaN,NaN
22,2026-07-15T09:32:10Z,https://www.adzuna.com.br/land/ad/5801146046?s...,A Iguatemi Empresa de Shopping Centers S.A. é ...,5801146046,0,ANALISTA DE GOVERNANÇA DE DADOS SR.,Iguatemi S.A.,"São Paulo, Estado de São Paulo",NaN,NaN
23,2026-07-05T17:03:19Z,https://www.adzuna.com.br/land/ad/5789297995?s...,Venha para uma das maiores empresas de Serviç...,5789297995,0,Engenheiro de Dados Sênior – Databricks,Tata Consultancy Services,Brasil,NaN,NaN
24,2026-07-04T16:53:37Z,https://www.adzuna.com.br/land/ad/5788222351?s...,CLT Local: Campinas SP Modelo: presencial Sobr...,5788222351,0,Gerente de Dados I | SAP,AB InBev,"Campinas, Estado de São Paulo",-22.98889,-47.14058