In [1]:
import json
import pandas as pd
from pathlib import Path

In [2]:
reg = []
for file in Path("../bronze/data/records").glob("*.jsonl"):
    with open(file, encoding="utf-8") as f:
        for line in f:
            payload = json.loads(line)
            reg.extend(payload["results"])

In [3]:
df = pd.DataFrame(pd.json_normalize(reg))

In [4]:
raw_lines, raw_columns = df.shape

In [5]:
df = df.drop_duplicates(subset="id", keep="last")

In [6]:
df.head()

,__CLASS__,redirect_url,salary_is_predicted,title,created,adref,description,id,company.__CLASS__,company.display_name,...,location.display_name,category.tag,category.label,category.__CLASS__,latitude,longitude,salary_min,contract_time,salary_max,contract_type
0,Adzuna::API::Response::Job,https://www.adzuna.com.br/land/ad/5805100299?s...,0,Arquiteto de Dados,2026-07-17T15:26:35Z,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgwNTEwMDI5OSIsI...,Estamos buscando um(a) Arquiteto(a) de Dados p...,5805100299,Adzuna::API::Response::Company,HVAR,...,"Rio de Janeiro, Estado do Rio de Janeiro",it-jobs,Vagas em Tecnologia Informática,Adzuna::API::Response::Category,NaN,NaN,NaN,NaN,NaN,NaN
1,Adzuna::API::Response::Job,https://www.adzuna.com.br/land/ad/5801466951?s...,0,Analista de Dados,2026-07-15T15:19:13Z,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgwMTQ2Njk1MSIsI...,Analista de Dados / Controller Financeiro – Ba...,5801466951,Adzuna::API::Response::Company,Barbearia do Rapha,...,"Belo Horizonte, Minas Gerais",social-work-jobs,Vagas em Serviços Sociais,Adzuna::API::Response::Category,-19.910956,-44.035061,NaN,NaN,NaN,NaN
2,Adzuna::API::Response::Job,https://www.adzuna.com.br/land/ad/5803425208?s...,0,Engenheiro(a) de Dados Sênior,2026-07-16T13:56:53Z,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiek5KNGYtaUM4UkdGN...,Estamos buscando por um Engenheiro(a) de Dados...,5803425208,Adzuna::API::Response::Company,Nava | Tech for Business,...,"São Paulo, Estado de São Paulo",unknown,Unknown,Adzuna::API::Response::Category,NaN,NaN,NaN,NaN,NaN,NaN
8,Adzuna::API::Response::Job,https://www.adzuna.com.br/land/ad/5804793804?s...,0,Especialista em gestão comercial & dados,2026-07-17T07:25:46Z,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiek5KNGYtaUM4UkdGN...,Especialista em Gestão Comercial & Dados Estam...,5804793804,Adzuna::API::Response::Company,Organização Verdemar,...,"Belo Horizonte, Minas Gerais",retail-jobs,Vagas em Varejo,Adzuna::API::Response::Category,-19.910956,-44.035061,NaN,NaN,NaN,NaN
10,Adzuna::API::Response::Job,https://www.adzuna.com.br/land/ad/5806312153?s...,0,Especialista de Dados – Crédito e Risco (Hibrido),2026-07-18T15:29:25Z,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgwNjMxMjE1MyIsI...,"A Foursys é um time apaixonado por inovação, d...",5806312153,Adzuna::API::Response::Company,FOURSYS,...,"Barueri, Estado de São Paulo",it-jobs,Vagas em Tecnologia Informática,Adzuna::API::Response::Category,-23.950450,-46.278770,NaN,NaN,NaN,NaN

In [7]:
new_lines, new_columns = df.shape

print(f"{raw_lines - new_lines} lines were deleted")

37 lines were deleted

In [8]:
df = df.drop(columns = ["adref", "__CLASS__", "company.__CLASS__", "category.label", "category.tag", "location.area", "category.__CLASS__", "location.__CLASS__", "latitude","longitude"])

In [9]:
df = df.rename(columns={'created':"collected_at", 'redirect_url':"url", 'salary_is_predicted':"salary", 'company.display_name':"company",'location.area':"local", 'location.display_name':"location"})

In [10]:
df = df.drop_duplicates()

In [11]:
df.head()

,url,salary,title,collected_at,description,id,company,location,salary_min,contract_time,salary_max,contract_type
0,https://www.adzuna.com.br/land/ad/5805100299?s...,0,Arquiteto de Dados,2026-07-17T15:26:35Z,Estamos buscando um(a) Arquiteto(a) de Dados p...,5805100299,HVAR,"Rio de Janeiro, Estado do Rio de Janeiro",NaN,NaN,NaN,NaN
1,https://www.adzuna.com.br/land/ad/5801466951?s...,0,Analista de Dados,2026-07-15T15:19:13Z,Analista de Dados / Controller Financeiro – Ba...,5801466951,Barbearia do Rapha,"Belo Horizonte, Minas Gerais",NaN,NaN,NaN,NaN
2,https://www.adzuna.com.br/land/ad/5803425208?s...,0,Engenheiro(a) de Dados Sênior,2026-07-16T13:56:53Z,Estamos buscando por um Engenheiro(a) de Dados...,5803425208,Nava | Tech for Business,"São Paulo, Estado de São Paulo",NaN,NaN,NaN,NaN
8,https://www.adzuna.com.br/land/ad/5804793804?s...,0,Especialista em gestão comercial & dados,2026-07-17T07:25:46Z,Especialista em Gestão Comercial & Dados Estam...,5804793804,Organização Verdemar,"Belo Horizonte, Minas Gerais",NaN,NaN,NaN,NaN
10,https://www.adzuna.com.br/land/ad/5806312153?s...,0,Especialista de Dados – Crédito e Risco (Hibrido),2026-07-18T15:29:25Z,"A Foursys é um time apaixonado por inovação, d...",5806312153,FOURSYS,"Barueri, Estado de São Paulo",NaN,NaN,NaN,NaN